#!/usr/bin/env bash

. $(dirname $0)/util
set -eu

: ${TARGET=releaser}
: ${OUTPUT_DIR=./_build}
: ${CONTAINER_BUILD_DIR=./_build}
: ${OUTPUT_FORMAT="type=local,dest=$OUTPUT_DIR"}

if [ -n "$BUILDKIT_HOST" ] && buildctl --version >/dev/null 2>&1; then
  targetFlags=""
  if [ -n "$TARGET" ]; then
    targetFlags="--opt target=$TARGET"
  fi
  buildctlCmd build \
      $targetFlags \
      --frontend=dockerfile.v0 \
      --build-arg=BUILD_DIR=$CONTAINER_BUILD_DIR \
      --local context=. \
      --local dockerfile=. \
      --output="$OUTPUT_FORMAT"
else
  targetFlags=""
  if [ -n "$TARGET" ]; then
    targetFlags="--target $TARGET"
  fi
  buildxCmd build \
    $targetFlags \
      --output="$OUTPUT_FORMAT" \
      --build-arg=BUILD_DIR=$CONTAINER_BUILD_DIR \
      .
fi
